language: go
go:
  - 1.11.x
  - 1.12.x
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database ci_test;' -U postgres
env:
  - GO111MODULE=on DATABASE_DSN=postgres://127.0.0.1/ci_test
cache:
  directories:
    - $GOPATH/pkg/mod