language: go
go:
  - 1.14.x
  - 1.15.x
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database ci_test;' -U postgres
env:
  - DATABASE_DSN=postgres://127.0.0.1/ci_test
cache:
  directories:
    - $GOPATH/pkg/mod
